const _0x47927d = [
    {
        id: 0x1,
        text: "限时抢购",
        children: [
            {
                flow: 0xa,
                price: 0xa,
                sellNum: 0x1a0,
                type: 0x1,
                typeName: "人气",
                unit: "GB",
                dateUnit: "次",
                name: "10GB3日包",
                reFlow: "10GB",
                productId: "90991668",
                productName: "10元10GB3日包",
                path: "orderPage",
                commIds: "974208284006",
                ids: ["91326331", "91326194", "91326361"],
                productName2: "10元10GB3日包+10元18GB单日包",
                reFlow2: "28GB",
            },
            {
                flow: 0x6,
                price: 0xa,
                sellNum: 0x253,
                commId: "974209251316",
                templateFlag: "1",
                type: 0x1,
                typeName: "推荐",
                unit: "GB",
                reFlow: "6GB",
                dateUnit: "次",
                name: "6GB5日包",
                productId: "91258941",
                productIds: ["90987862"],
                productName: "10元6GB5日包",
                path: "orderPage",
                commIds: "974209251321",
                ids: ["90987862", "91326331", "91326194", "91326361"],
                productName2: "10元6GB5日包+10元18GB单日包",
                reFlow2: "24GB",
            },
            {
                flow: 0x13,
                price: 0x15,
                sellNum: 0x2ec,
                commId: "974203075988",
                templateFlag: "1",
                type: 0x1,
                typeName: "送会员",
                unit: "GB",
                reFlow: "19GB",
                dateUnit: "次",
                name: "19GB7日包",
                productId: "91008468",
                productIds: ["91326378"],
                productName: "21元19GB7日包",
                path: "orderPage",
                commIds: "974208049796",
                ids: ["91326378", "91326331", "91326194", "91326361"],
                productName2: "21元19GB7日包+10元18GB单日特惠包",
                reFlow2: "37GB",
            },
            {
                flow: 0xf,
                price: 0x15,
                sellNum: 0x2ec,
                commId: "974208283987",
                templateFlag: "1",
                type: 0x2,
                typeName: "强烈推荐",
                unit: "GB",
                reFlow: "15GB",
                dateUnit: "次",
                name: "15GB10日包",
                productId: "91326350",
                productIds: ["91326385"],
                productName: "21元15GB10日包",
                path: "orderPage",
                commIds: "974208284008",
                ids: ["91326385", "91326331", "91326194", "91326361"],
                productName2: "21元15GB10日包+10元18GB单日包",
                reFlow2: "33GB",
            },
            {
                flow: 0x14,
                price: 0x1f,
                sellNum: 0x2ec,
                commId: "974203297376",
                templateFlag: "1",
                type: 0x2,
                typeName: "爆款",
                unit: "GB",
                reFlow: "20GB",
                dateUnit: "次",
                name: "20GB月包",
                productId: "91326526",
                productIds: ["91326533"],
                productName: "31元20GB月包",
                path: "orderPage",
                commIds: "974206163190",
                ids: ["91326533", "91326331", "91326194", "91326361"],
                productName2: "31元20GB月包+10元18GB单日特惠包",
                reFlow2: "38GB",
            },
        ],
    },
    {
        id: 0x2,
        text: "超值月包",
        children: [
            {
                flow: 0xa,
                price: 0x14,
                sellNum: 0x5cb,
                type: 0x2,
                typeName: "超级热卖",
                unit: "GB",
                dateUnit: "月",
                name: "10GB",
                reFlow: "10GB",
                productId: "91326524",
                productName: "20元10GB月包",
                path: "orderPage",
                commIds: "974208049798",
                ids: ["91326331", "91326194", "91326361"],
                productName2: "20元10GB月包+10元18GB单日特惠包",
                reFlow2: "28GB",
            },
            {
                flow: 0x14,
                price: 0x1f,
                sellNum: 0x1ab,
                commId: "974203297376",
                templateFlag: "1",
                type: 0x2,
                typeName: "爆款推荐",
                unit: "GB",
                reFlow: "20GB",
                dateUnit: "月",
                name: "20GB",
                productId: "91326526",
                productIds: ["91326533"],
                productName: "31元20GB月包",
                path: "orderPage",
                commIds: "974206163190",
                ids: ["91326533", "91326331", "91326194", "91326361"],
                productName2: "31元20GB月包+10元18GB单日特惠包",
                reFlow2: "38GB",
            },
            {
                flow: 0x1e,
                price: 0x2a,
                sellNum: 0x234,
                commId: "974203297377",
                templateFlag: "1",
                type: 0x1,
                typeName: "推荐",
                unit: "GB",
                reFlow: "30GB",
                dateUnit: "月",
                name: "30GB",
                productId: "91326528",
                productIds: ["91326532"],
                productName: "42元30GB月包",
                path: "orderPage",
                commIds: "974206163191",
                ids: ["91326532", "91326331", "91326194", "91326361"],
                productName2: "42元30GB月包+10元18GB单日特惠包",
                reFlow2: "48GB",
            },
            {
                flow: 0x2d,
                price: 0x36,
                sellNum: 0x1db,
                commId: "974206119385",
                templateFlag: "1",
                type: 0x1,
                typeName: "超值",
                unit: "GB",
                reFlow: "45GB",
                dateUnit: "月",
                name: "45GB",
                productId: "91326530",
                productIds: ["91326345", "91326349"],
                productName: "54元45GB组合月包",
                path: "orderPage",
                commIds: "974206163192",
                ids: ["91326345", "91326349", "91326331", "91326194", "91326361"],
                productName2: "54元45GB特惠组合月包+10元18GB单日特惠包",
                reFlow2: "63GB",
            },
        ],
    },
    {
        id: 0x3,
        text: "10日包",
        children: [
            {
                flow: 0x9,
                price: 0x10,
                sellNum: 0x253,
                commId: "974208283984",
                templateFlag: "1",
                type: 0x1,
                typeName: "人气",
                unit: "GB",
                reFlow: "9GB",
                dateUnit: "次",
                name: "9GB",
                productId: "91326206",
                productIds: ["91326385"],
                productName: "16元9GB10日包",
                path: "orderPage",
                commIds: "974208284003",
                ids: ["91326385", "91326331", "91326194", "91326361"],
                productName2: "16元9GB10日包+10元18GB单日包",
                reFlow2: "27GB",
            },
            {
                flow: 0xf,
                price: 0x15,
                sellNum: 0x2a0,
                commId: "974208283987",
                templateFlag: "1",
                type: 0x1,
                typeName: "特惠",
                unit: "GB",
                reFlow: "15GB",
                dateUnit: "次",
                name: "15GB",
                productId: "91326350",
                productIds: ["91326385"],
                productName: "21元15GB10日包",
                path: "orderPage",
                commIds: "974208284008",
                ids: ["91326385", "91326331", "91326194", "91326361"],
                productName2: "21元15GB10日包+10元18GB单日包",
                reFlow2: "33GB",
            },
            {
                flow: 0x1e,
                price: 0x21,
                sellNum: 0x1eb,
                commId: "974206119248",
                templateFlag: "1",
                type: 0x2,
                typeName: "热卖新品",
                unit: "GB",
                reFlow: "30GB",
                dateUnit: "次",
                name: "30GB",
                productId: "91326351",
                productIds: ["91326385", "91326349"],
                productName: "33元30GB10日包",
                path: "orderPage",
                commIds: "974208049797",
                ids: ["91326385", "91326349", "91326331", "91326194", "91326361"],
                productName2: "33元30GB10日包+10元18GB单日特惠包",
                reFlow2: "48GB",
            },
            {
                flow: 0x23,
                price: 0x25,
                sellNum: 0x217,
                commId: "974208283988",
                templateFlag: "1",
                type: 0x2,
                typeName: "巨实惠",
                unit: "GB",
                reFlow: "35GB",
                dateUnit: "次",
                name: "35GB",
                productId: "91319744",
                productIds: ["91326349"],
                productName: "37元35GB10日包",
                path: "orderPage",
                commIds: "974208284011",
                ids: ["91326349", "91326331", "91326194", "91326361"],
                productName2: "37元35GB10日包+10元18GB单日包",
                reFlow2: "53GB",
            },
        ],
    },
    {
        id: 0x4,
        text: "7日包",
        children: [
            {
                flow: 0xe,
                price: 0x12,
                sellNum: 0x34d1,
                commId: "974210110141",
                type: 0x2,
                typeName: "惊喜特惠",
                unit: "GB",
                dateUnit: "次",
                name: "14GB",
                reFlow: "14GB",
                productId: "91057749",
                productIds: ["90987862"],
                productName: "18元14GB7天包（惊喜版）",
                path: "orderPage",
                commIds: "974208284012",
                ids: ["91326331", "91326194", "91326361"],
                productName2: "18元14GB7日包+10元18GB单日包",
                reFlow2: "32GB",
            },
            {
                flow: 0x13,
                price: 0x15,
                sellNum: 0x273,
                commId: "974203075988",
                templateFlag: "1",
                type: 0x1,
                typeName: "送会员",
                unit: "GB",
                reFlow: "19GB",
                dateUnit: "次",
                name: "19GB",
                productId: "91008468",
                productIds: ["91326378"],
                productName: "21元19GB7日包",
                path: "orderPage",
                commIds: "974208049796",
                ids: ["91326378", "91326331", "91326194", "91326361"],
                productName2: "21元19GB7日包+10元18GB单日特惠包",
                reFlow2: "37GB",
            },
            {
                flow: 0x1f,
                price: 0x1b,
                sellNum: 0x23d,
                commId: "974208283989",
                templateFlag: "1",
                type: 0x2,
                typeName: "热门",
                unit: "GB",
                reFlow: "31GB",
                dateUnit: "次",
                name: "31GB",
                productId: "91057751",
                productIds: ["91326345"],
                productName: "27元31GB7日包",
                path: "orderPage",
                commIds: "974208284013",
                ids: ["91326345", "91326331", "91326194", "91326361"],
                productName2: "27元31GB7日包+10元18GB单日包",
                reFlow2: "49GB",
            },
            {
                flow: 0x23,
                price: 0x21,
                sellNum: 0x2b3,
                commId: "974208283990",
                templateFlag: "1",
                type: 0x1,
                typeName: "畅销",
                unit: "GB",
                reFlow: "35GB",
                dateUnit: "次",
                name: "35GB",
                productId: "91295482",
                productIds: ["91326345", "91326378"],
                productName: "33元35GB7日包",
                path: "orderPage",
                commIds: "974208284014",
                ids: ["91326345", "91326378", "91326331", "91326194", "91326361"],
                productName2: "33元35GB7日包+10元18GB单日包",
                reFlow2: "53GB",
            },
            {
                flow: 0x1a,
                price: 0x1a,
                sellNum: 0x2b3,
                commId: "974208294626",
                templateFlag: "1",
                type: 0x1,
                typeName: "限购",
                unit: "GB",
                reFlow: "26GB",
                dateUnit: "次",
                name: "26GB",
                productId: "91057751",
                productIds: ["91326378"],
                productName: "26元26GB7日包",
                path: "orderPage",
            },
        ],
    },
    {
        id: 0x5,
        text: "5日包",
        children: [
            {
                flow: 0x6,
                price: 0xa,
                sellNum: 0x222,
                commId: "974209251316",
                templateFlag: "1",
                type: 0x0,
                typeName: "",
                unit: "GB",
                reFlow: "6GB",
                dateUnit: "次",
                name: "6GB",
                productId: "91258941",
                productIds: ["90987862"],
                productName: "10元6GB5日包",
                path: "orderPage",
                commIds: "974209251321",
                ids: ["90987862", "91326331", "91326194", "91326361"],
                productName2: "10元6GB5日包+10元18GB单日包",
                reFlow2: "24GB",
            },
            {
                flow: 0x10,
                price: 0x11,
                sellNum: 0x160,
                commId: "974208283985",
                templateFlag: "1",
                type: 0x1,
                typeName: "热门",
                unit: "GB",
                reFlow: "16GB",
                dateUnit: "次",
                name: "16GB",
                productId: "91326201",
                productIds: ["91326342"],
                productName: "17元16GB5日包",
                path: "orderPage",
                commIds: "974208284004",
                ids: ["91326342", "91326331", "91326194", "91326361"],
                productName2: "17元16GB5日包+10元18GB单日包",
                reFlow2: "34GB",
            },
            {
                flow: 0x13,
                price: 0x16,
                sellNum: 0x146,
                commId: "974203012551",
                templateFlag: "1",
                type: 0x2,
                typeName: "巨实惠",
                unit: "GB",
                reFlow: "19GB",
                dateUnit: "次",
                name: "19GB",
                productId: "91326202",
                productIds: ["91326342"],
                productName: "22元19GB5日包",
                path: "orderPage",
                commIds: "974206120893",
                ids: ["91326342", "91326331", "91326194", "91326361"],
                productName2: "22元19GB5日包+10元18GB单日特惠包",
                reFlow2: "37GB",
            },
        ],
    },
    {
        id: 0x6,
        text: "3日包",
        children: [
            {
                flow: 0xa,
                price: 0xa,
                sellNum: 0x4b22,
                type: 0x0,
                typeName: "",
                unit: "GB",
                dateUnit: "次",
                name: "10GB",
                reFlow: "10GB",
                productId: "90991668",
                productName: "10元10GB3日包",
                path: "orderPage",
                commIds: "974208284006",
                ids: ["91326331", "91326194", "91326361"],
                productName2: "10元10GB3日包+10元18GB单日包",
                reFlow2: "28GB",
            },
            {
                flow: 0xe,
                price: 0xc,
                sellNum: 0x1a9,
                commId: "974208283991",
                templateFlag: "1",
                type: 0x1,
                typeName: "推荐",
                unit: "GB",
                reFlow: "14GB",
                dateUnit: "次",
                name: "14GB",
                productId: "91326197",
                productIds: ["91326341"],
                productName: "12元14GB3日包",
                path: "orderPage",
                commIds: "974208284018",
                ids: ["91326341", "91326331", "91326194", "91326361"],
                productName2: "12元14GB3日包+10元18GB单日包",
                reFlow2: "32GB",
            },
            {
                flow: 0x14,
                price: 0x11,
                sellNum: 0x4c9,
                commId: "974208283992",
                templateFlag: "1",
                type: 0x2,
                typeName: "热卖新品",
                unit: "GB",
                reFlow: "20GB",
                dateUnit: "次",
                name: "20GB",
                productId: "91295475",
                productIds: ["91326341"],
                productName: "17元20GB3日包",
                path: "orderPage",
                commIds: "974208284019",
                ids: ["91326341", "91326331", "91326194", "91326361"],
                productName2: "17元20GB3日包+10元18GB单日包",
                reFlow2: "38GB",
            },
        ],
    },
    {
        id: 0x7,
        text: "单日包",
        children: [
            {
                flow: 0x3,
                price: 0x7,
                sellNum: 0x19d,
                type: 0x1,
                typeName: "优惠单品",
                unit: "GB",
                dateUnit: "次",
                name: "3GB",
                reFlow: "3GB",
                productId: "91326194",
                productName: "7元3GB单日包",
                path: "orderPage",
            },
            {
                flow: 0xd,
                price: 0xa,
                sellNum: 0x311,
                commId: "974208283993",
                templateFlag: "1",
                type: 0x0,
                typeName: "",
                unit: "GB",
                reFlow: "13GB",
                dateUnit: "次",
                name: "13GB",
                productId: "91326193",
                productIds: ["91326181", "91326331"],
                productName: "10元13GB单日包",
                path: "orderPage",
            },
            {
                flow: 0xf,
                price: 0xe,
                sellNum: 0x365,
                commId: "974206119394",
                templateFlag: "1",
                type: 0x1,
                typeName: "热门",
                unit: "GB",
                reFlow: "15GB",
                dateUnit: "次",
                name: "15GB",
                productId: "91326193",
                productIds: ["91326194", "91326331"],
                productName: "14元15GB单日组合包",
                path: "orderPage",
            },
        ],
    },
];

const _0x3e0a16 = [
    {
        id: 0x1,
        text: "限时福利",
        children: [
            {
                flow: 0xc,
                price: 0x15,
                sellNum: 0x1a9,
                commId: "974206119383",
                templateFlag: "1",
                type: 0x1,
                typeName: "热门",
                unit: "GB",
                reFlow: "12GB",
                dateUnit: "次",
                name: "12GB10日包",
                productId: "91326207",
                productIds: ["91326385"],
                productName: "21元12GB10日包",
                path: "orderPage",
            },
            {
                flow: 0x19,
                price: 0x20,
                sellNum: 0x253,
                commId: "974203075990",
                templateFlag: "1",
                type: 0x1,
                typeName: "畅销",
                unit: "GB",
                reFlow: "25GB",
                dateUnit: "次",
                name: "25GB7日包",
                productId: "91326348",
                productIds: ["91326345"],
                productName: "32元25GB7日包",
                path: "orderPage",
            },
            {
                flow: 0x1e,
                price: 0x2a,
                sellNum: 0x2ec,
                commId: "974203297377",
                templateFlag: "1",
                type: 0x2,
                typeName: "强烈推荐",
                unit: "GB",
                reFlow: "30GB",
                dateUnit: "次",
                name: "30GB月包",
                productId: "91326528",
                productIds: ["91326532"],
                productName: "42元30GB月包（特惠组合版）",
                path: "orderPage",
            },
            {
                flow: 0x13,
                price: 0x16,
                sellNum: 0x2ec,
                commId: "974203012551",
                templateFlag: "1",
                type: 0x1,
                typeName: "推荐",
                unit: "GB",
                reFlow: "19GB",
                dateUnit: "次",
                name: "19GB5日包",
                productId: "91326202",
                productIds: ["91326342"],
                productName: "22元19GB5日包",
                path: "orderPage",
            },
            {
                flow: 0xf,
                price: 0x1e,
                sellNum: 0x12e0,
                commIds: "974205300551",
                ids: ["91238517"],
                type: 0x0,
                typeName: "",
                unit: "GB",
                dateUnit: "月",
                name: "15GB月包",
                reFlow: "15GB",
                productId: "91326546",
                productName: "黑龙江-30元15GB国内5G流量月包（立即生效）",
                productName2: "黑龙江-30元15GB国内5G流量月包（立即生效）+视频彩铃铂金会员",
                path: "orderPage",
            },
            {
                flow: 0x19,
                price: 0x23,
                sellNum: 0x1a9,
                commId: "974206206421",
                templateFlag: "1",
                type: 0x1,
                typeName: "新品",
                unit: "GB",
                reFlow: "25GB",
                dateUnit: "次",
                name: "25GB10日包",
                productId: "91319744",
                productName: "35元25GB10天国内流量包",
                commIds: "974207195038",
                ids: ["91326331", "91326361", "91326194", "91319744"],
                productName2: "35元25GB10天流量包+10元18GB单日特惠包",
                reFlow2: "35GB",
                commIds2: "974207195054",
                ids2: ["91319744", "91238517"],
                productName3: "35元25GB10天流量包+视频彩铃铂金会员",
                reFlow3: "25GB",
                path: "orderPage",
            },
        ],
    },
    {
        id: 0x2,
        text: "加速包",
        children: [
            {
                flow: 0x3,
                price: 0xf,
                sellNum: 0x1a0,
                type: 0x1,
                typeName: "单次版",
                unit: "GB",
                dateUnit: "次",
                name: "3GB",
                reFlow: "3GB",
                productId: "90350650",
                productName: "冰激凌加速包单次版",
                path: "orderPage",
            },
        ],
    },
    {
        id: 0x3,
        text: "特惠月包",
        children: [
            {
                flow: 0x14,
                price: 0x1f,
                sellNum: 0x4dc,
                commId: "974203297376",
                templateFlag: "1",
                type: 0x1,
                typeName: "推荐",
                unit: "GB",
                reFlow: "20GB",
                dateUnit: "次",
                name: "20GB",
                productId: "91326526",
                productIds: ["91326533"],
                productName: "31元20GB月包（特惠组合版）",
                path: "orderPage",
            },
            {
                flow: 0x1e,
                price: 0x2a,
                sellNum: 0x3a8,
                commId: "974203297377",
                templateFlag: "1",
                type: 0x2,
                typeName: "强烈推荐",
                unit: "GB",
                reFlow: "30GB",
                dateUnit: "次",
                name: "30GB",
                productId: "91326528",
                productIds: ["91326532"],
                productName: "42元30GB月包（特惠组合版）",
                path: "orderPage",
            },
            {
                flow: 0x2d,
                price: 0x36,
                sellNum: 0xee,
                commId: "974206119385",
                templateFlag: "1",
                type: 0x1,
                typeName: "超值",
                unit: "GB",
                reFlow: "45GB",
                dateUnit: "次",
                name: "45GB",
                productId: "91326530",
                productIds: ["91326349", "91326345"],
                productName: "54元45GB特惠组合包",
                path: "orderPage",
            },
        ],
    },
    {
        id: 0x4,
        text: "10日包",
        children: [
            {
                flow: 0xc,
                price: 0x15,
                sellNum: 0x1476,
                commId: "974206119383",
                templateFlag: "1",
                type: 0x1,
                typeName: "热门",
                unit: "GB",
                reFlow: "12GB",
                dateUnit: "次",
                name: "12GB",
                productId: "91326207",
                productIds: ["91326385"],
                productName: "21元12GB10日包",
                path: "orderPage",
            },
            {
                flow: 0x14,
                price: 0x1f,
                sellNum: 0x486,
                commId: "974206119387",
                templateFlag: "1",
                type: 0x1,
                typeName: "畅销",
                unit: "GB",
                reFlow: "20GB",
                dateUnit: "次",
                name: "20GB",
                productId: "91326351",
                productIds: ["91326385"],
                productName: "31元20GB10日包",
                path: "orderPage",
            },
            {
                flow: 0x23,
                price: 0x2b,
                sellNum: 0x19c,
                commId: "974206119390",
                templateFlag: "1",
                type: 0x0,
                typeName: "",
                unit: "GB",
                reFlow: "35GB",
                dateUnit: "次",
                name: "35GB",
                productId: "91326209",
                productIds: ["91326349", "91326385"],
                productName: "43元35GB10日包",
                path: "orderPage",
            },
            {
                flow: 0xc,
                price: 0x1e,
                sellNum: 0x1ab,
                type: 0x2,
                typeName: "推荐",
                unit: "GB",
                dateUnit: "次",
                name: "12GB",
                reFlow: "12GB",
                productId: "91326381",
                productName: "黑龙江-30元12GB全国5G流量10日包",
                path: "orderPage",
            },
            {
                flow: 0x7,
                price: 0x14,
                sellNum: 0x133,
                type: 0x0,
                typeName: "",
                unit: "GB",
                dateUnit: "次",
                name: "7GB",
                reFlow: "7GB",
                productId: "91326380",
                productName: "黑龙江-20元7GB全国5G流量10日包",
                path: "orderPage",
            },
            {
                flow: 0x4,
                price: 0xf,
                sellNum: 0x1eb,
                type: 0x0,
                typeName: "",
                unit: "GB",
                dateUnit: "次",
                name: "4GB",
                reFlow: "4GB",
                productId: "91326379",
                productName: "黑龙江-15元4GB全国5G流量10日包",
                path: "orderPage",
            },
            {
                flow: 0xc,
                price: 0x23,
                sellNum: 0x1a9,
                commId: "974206206421",
                templateFlag: "1",
                type: 0x1,
                typeName: "新品",
                unit: "GB",
                reFlow: "12GB",
                dateUnit: "次",
                name: "25GB10日包",
                productId: "91319744",
                productName: "35元25GB10天国内流量包",
                commIds: "974207195038",
                ids: ["91326331", "91326361", "91326194", "91319744"],
                productName2: "35元25GB10天流量包+10元18GB单日特惠包",
                reFlow2: "35GB",
                commIds2: "974207195054",
                ids2: ["91319744", "91238517"],
                productName3: "35元25GB10天流量包+视频彩铃铂金会员",
                reFlow3: "25GB",
                path: "orderPage",
            },
        ],
    },
    {
        id: 0x5,
        text: "7日包",
        children: [
            {
                flow: 0x19,
                price: 0x20,
                sellNum: 0x1a9,
                commId: "974203075990",
                templateFlag: "1",
                type: 0x1,
                typeName: "推荐",
                unit: "GB",
                reFlow: "25GB",
                dateUnit: "次",
                name: "25GB",
                productId: "91326348",
                productIds: ["91326345"],
                productName: "32元25GB7日包",
                path: "orderPage",
            },
            {
                flow: 0x14,
                price: 0x1e,
                sellNum: 0x4b22,
                type: 0x2,
                typeName: "爆款",
                unit: "GB",
                dateUnit: "次",
                name: "20GB",
                reFlow: "20GB",
                productId: "91295482",
                commIds: "974205300549",
                ids: ["91238517"],
                productName: "30元20GB7天国内流量包",
                path: "orderPage",
            },
            {
                flow: 0xe,
                price: 0x14,
                sellNum: 0x3bf1,
                type: 0x1,
                typeName: "送会员",
                unit: "GB",
                dateUnit: "次",
                name: "14GB",
                reFlow: "14GB",
                productId: "91008468",
                productName: "20元包7天假日包流量翻倍享14GB",
                path: "orderPage",
            },
            {
                flow: 0x5,
                price: 0xf,
                sellNum: 0x265,
                type: 0x0,
                typeName: "",
                unit: "GB",
                dateUnit: "次",
                name: "5GB",
                reFlow: "5GB",
                productId: "91326375",
                productName: "黑龙江-15元5GB全国5G流量7日包",
                path: "orderPage",
            },
            {
                flow: 0xa,
                price: 0x14,
                sellNum: 0x1a5,
                type: 0x2,
                typeName: "推荐",
                unit: "GB",
                dateUnit: "次",
                name: "10GB",
                reFlow: "10GB",
                productId: "91326377",
                productName: "黑龙江-20元10GB全国5G流量7日包",
                path: "orderPage",
            },
        ],
    },
    {
        id: 0x6,
        text: "5日包",
        children: [
            {
                flow: 0x13,
                price: 0x16,
                sellNum: 0x222,
                commId: "974203012551",
                commIds: "974205300523",
                ids: ["91326342", "91238517"],
                templateFlag: "1",
                type: 0x2,
                typeName: "推荐",
                unit: "GB",
                reFlow: "19GB",
                dateUnit: "次",
                name: "19GB",
                productId: "91326202",
                productIds: ["91326342"],
                productName: "22元19GB5日包",
                productName2: "22元19GB5日包+视频彩铃铂金会员",
                path: "orderPage",
            },
            {
                flow: 0xb,
                price: 0x10,
                sellNum: 0x160,
                commId: "974203012552",
                commIds: "974205300527",
                ids: ["91326373", "91238517"],
                templateFlag: "1",
                type: 0x2,
                typeName: "热销",
                unit: "GB",
                reFlow: "11GB",
                dateUnit: "次",
                name: "11GB",
                productId: "91326201",
                productIds: ["91326373"],
                productName: "16元11GB5日包",
                productName2: "16元11GB5日包+视频彩铃铂金会员",
                path: "orderPage",
            },
            {
                flow: 0x5,
                price: 0xa,
                sellNum: 0x534,
                type: 0x0,
                typeName: "",
                unit: "GB",
                dateUnit: "次",
                name: "5GB",
                reFlow: "5GB",
                productId: "91258941",
                productName: "10元5GB5天国内流量包（立即生效）",
                path: "orderPage",
            },
            {
                flow: 0xf,
                price: 0x1e,
                sellNum: 0x23d,
                type: 0x2,
                typeName: "热销",
                unit: "GB",
                dateUnit: "次",
                name: "15GB",
                reFlow: "15GB",
                productId: "91326372",
                productName: "黑龙江-30元15GB国内5G流量5日包",
                path: "orderPage",
            },
            {
                flow: 0x9,
                price: 0x14,
                sellNum: 0x23d,
                type: 0x0,
                typeName: "",
                unit: "GB",
                dateUnit: "次",
                name: "9GB",
                reFlow: "9GB",
                productId: "91326369",
                productName: "黑龙江-20元9GB全国5G流量5日包",
                path: "orderPage",
            },
            {
                flow: 0x6,
                price: 0xf,
                sellNum: 0x146,
                type: 0x0,
                typeName: "",
                unit: "GB",
                dateUnit: "次",
                name: "6GB",
                reFlow: "6GB",
                commIds: "974205300561",
                ids: ["91238517"],
                productId: "91326368",
                productName: "15元6GB全国5G流量5日包",
                productName2: "15元6GB全国5G流量5日包+视频彩铃铂金会员",
                path: "orderPage",
            },
        ],
    },
    {
        id: 0x7,
        text: "三日包",
        children: [
            {
                flow: 0x10,
                price: 0x12,
                sellNum: 0x225,
                commId: "974206119392",
                templateFlag: "1",
                type: 0x1,
                typeName: "推荐",
                unit: "GB",
                reFlow: "16GB",
                dateUnit: "次",
                name: "16GB",
                productId: "91326197",
                productIds: ["91326341", "91326196"],
                productName: "18元16GB3日包",
                path: "orderPage",
            },
            {
                flow: 0xa,
                price: 0xf,
                sellNum: 0x34d1,
                type: 0x1,
                typeName: "热门",
                unit: "GB",
                dateUnit: "次",
                name: "10GB",
                reFlow: "10GB",
                productId: "91295475",
                productName: "15元10GB3天国内流量包",
                path: "orderPage",
            },
            {
                flow: 0x3,
                price: 0x7,
                sellNum: 0x2c44,
                type: 0x0,
                typeName: "",
                unit: "GB",
                dateUnit: "次",
                name: "3GB",
                reFlow: "3GB",
                productId: "91295467",
                productName: "7元3GB3天国内流量包",
                path: "orderPage",
            },
            {
                flow: 0xa,
                price: 0x14,
                sellNum: 0x4968,
                type: 0x2,
                typeName: "推荐",
                unit: "GB",
                dateUnit: "次",
                name: "10GB",
                reFlow: "10GB",
                commIds: "974205300560",
                ids: ["91238517"],
                productId: "91326365",
                productName: "20元10GB全国5G流量3日包",
                productName2: "20元10GB全国5G流量3日包+视频彩铃铂金会员",
                path: "orderPage",
            },
            {
                flow: 0x7,
                price: 0xf,
                sellNum: 0x304c,
                type: 0x0,
                typeName: "",
                unit: "GB",
                dateUnit: "次",
                name: "7GB",
                reFlow: "7GB",
                productId: "91326364",
                productName: "黑龙江-15元7GB全国5G流量3天包",
                path: "orderPage",
            },
            {
                flow: 0x4,
                price: 0xa,
                sellNum: 0x363,
                type: 0x0,
                typeName: "",
                unit: "GB",
                dateUnit: "次",
                name: "4GB",
                reFlow: "4GB",
                productId: "91326363",
                productName: "黑龙江-10元4GB国内5G流量3日包",
                path: "orderPage",
            },
        ],
    },
    {
        id: 0x8,
        text: "单日包",
        children: [
            {
                flow: 0xf,
                price: 0xe,
                sellNum: 0x19c,
                commId: "974206119394",
                templateFlag: "1",
                type: 0x0,
                typeName: "",
                unit: "GB",
                reFlow: "15GB",
                dateUnit: "次",
                name: "15GB",
                productId: "91326194",
                productIds: ["91326193", "91326331"],
                productName: "14元15GB单日包",
                path: "orderPage",
            },
            {
                flow: 0xa,
                price: 0xb,
                sellNum: 0x19c,
                commId: "974206119395",
                templateFlag: "1",
                type: 0x1,
                typeName: "热门",
                unit: "GB",
                reFlow: "10GB",
                dateUnit: "次",
                name: "10GB",
                productId: "91326195",
                productIds: ["91326361"],
                productName: "11元10GB单日包",
                path: "orderPage",
            },
            {
                flow: 0x3,
                price: 0x7,
                sellNum: 0x2c44,
                type: 0x0,
                typeName: "",
                unit: "GB",
                dateUnit: "次",
                name: "3GB",
                reFlow: "3GB",
                productId: "91326194",
                productName: "黑龙江-7元3GB国内流量日包",
                path: "orderPage",
            },
            {
                flow: 0x2,
                price: 0x5,
                sellNum: 0x4968,
                type: 0x0,
                typeName: "",
                unit: "GB",
                dateUnit: "次",
                name: "2GB",
                reFlow: "2GB",
                productId: "91326193",
                productName: "黑龙江-5元2GB国内流量日包",
                path: "orderPage",
            },
        ],
    },
    {
        id: 0x9,
        text: "王卡月包",
        children: [
            {
                flow: 0x3,
                price: 0x13,
                sellNum: 0x5cb,
                type: 0x1,
                typeName: "带权益",
                unit: "GB",
                dateUnit: "月",
                name: "3GB",
                reFlow: "3GB",
                productId: "91026316",
                productName: "5G超级会员白银版（19元3GB通用流量）立即生效",
                path: "orderPage",
            },
            {
                flow: 0x14,
                price: 0x27,
                sellNum: 0x5cb,
                type: 0x1,
                typeName: "带权益",
                unit: "GB",
                dateUnit: "月",
                name: "20GB",
                reFlow: "20GB",
                productId: "90996845",
                productName: "腾讯王卡-39元5G版超级会员（黄金版）-立即生效",
                path: "orderPage",
            },
            {
                flow: 0x28,
                price: 0x3b,
                sellNum: 0x5cb,
                type: 0x1,
                typeName: "带权益",
                unit: "GB",
                dateUnit: "月",
                name: "40GB",
                reFlow: "40GB",
                productId: "90993165",
                productName: "腾讯王卡-59元5G版超级会员（白金版）-立即生效",
                path: "orderPage",
            },
        ],
    },
    {
        id: 0xa,
        text: "加速月包",
        children: [
            {
                flow: 0x14,
                price: 0x28,
                sellNum: 0x5cb,
                type: 0x0,
                typeName: "",
                commIds: "974205300553",
                ids: ["91238517"],
                unit: "GB",
                dateUnit: "月",
                name: "20GB",
                reFlow: "20GB",
                productId: "91326548",
                productName: "黑龙江-40元20GB国内5G流量月包（立即生效）",
                productName2: "黑龙江-40元20GB国内5G流量月包（立即生效）+视频彩铃铂金会员",
                path: "orderPage",
            },
            {
                flow: 0x19,
                price: 0x32,
                sellNum: 0x5cb,
                type: 0x0,
                typeName: "",
                unit: "GB",
                dateUnit: "月",
                name: "25GB",
                reFlow: "25GB",
                commIds: "974205300557",
                ids: ["91238517"],
                productId: "91326550",
                productName: "黑龙江-50元25GB国内5G流量月包（立即生效）",
                productName2: "黑龙江-50元25GB国内5G流量月包（立即生效）+视频彩铃铂金会员",
                path: "orderPage",
            },
            {
                flow: 0x1e,
                price: 0x3c,
                sellNum: 0x5cb,
                type: 0x0,
                typeName: "",
                unit: "GB",
                dateUnit: "月",
                name: "30GB",
                reFlow: "30GB",
                productId: "91326542",
                productName: "黑龙江-60元30GB国内5G流量月包（立即生效）",
                path: "orderPage",
            },
            {
                flow: 0x2,
                price: 0x9,
                sellNum: 0x503,
                type: 0x1,
                typeName: "升级包",
                unit: "GB",
                dateUnit: "月",
                name: "2GB",
                reFlow: "2GB",
                productId: "90800035",
                productName: "5G升级包9元2GB（立即生效）",
                path: "orderPage",
            },
            {
                flow: 0x5,
                price: 0x13,
                sellNum: 0x5cb,
                type: 0x0,
                typeName: "",
                unit: "GB",
                dateUnit: "月",
                name: "5GB",
                reFlow: "5GB",
                productId: "90778507",
                productName: "5G升级包19元5GB（立即生效）",
                path: "orderPage",
            },
            {
                flow: 0xa,
                price: 0x1d,
                sellNum: 0x5cb,
                type: 0x0,
                typeName: "",
                unit: "GB",
                dateUnit: "月",
                name: "10GB",
                reFlow: "10GB",
                productId: "90759221",
                productName: "5G升级包29元10G（立即生效）",
                path: "orderPage",
            },
            {
                flow: 0x14,
                price: 0x31,
                sellNum: 0x5cb,
                type: 0x0,
                typeName: "",
                unit: "GB",
                dateUnit: "月",
                name: "20GB",
                reFlow: "20GB",
                productId: "90759226",
                productName: "5G升级包49元20G（立即生效）",
                path: "orderPage",
            },
        ],
    },
    {
        id: 0xb,
        text: "月包",
        children: [
            {
                flow: 0xf,
                price: 0x28,
                sellNum: 0x5cb,
                type: 0x1,
                typeName: "热门",
                unit: "GB",
                dateUnit: "月",
                name: "15GB",
                reFlow: "15GB",
                productId: "91326518",
                productName: "黑龙江-40元15GB国内流量月包（立即生效）",
                path: "orderPage",
            },
            {
                flow: 0x8,
                price: 0x1e,
                sellNum: 0x1fb,
                type: 0x0,
                typeName: "",
                unit: "GB",
                dateUnit: "月",
                name: "8GB",
                reFlow: "8GB",
                productId: "91326516",
                productName: "黑龙江-30元8GB全国流量月包（立即生效）",
                path: "orderPage",
            },
            {
                flow: 0x4,
                price: 0x14,
                sellNum: 0x13a,
                type: 0x0,
                typeName: "",
                unit: "GB",
                dateUnit: "月",
                name: "4GB",
                reFlow: "4GB",
                productId: "91326514",
                productName: "黑龙江-20元4GB国内流量月包（立即生效）",
                path: "orderPage",
            },
            {
                flow: 0x14,
                price: 0x32,
                sellNum: 0x103,
                type: 0x2,
                typeName: "推荐",
                unit: "GB",
                dateUnit: "月",
                name: "20GB",
                reFlow: "20GB",
                productId: "91326520",
                productName: "黑龙江-50元20GB全国流量月包（立即生效）",
                path: "orderPage",
            },
            {
                flow: 0x1e,
                price: 0x3c,
                sellNum: 0xb8,
                type: 0x0,
                typeName: "",
                unit: "GB",
                dateUnit: "月",
                name: "30GB",
                reFlow: "30GB",
                productId: "91326522",
                productName: "黑龙江-60元30GB国内流量月包（立即生效）",
                path: "orderPage",
            },
            {
                flow: 0x1e,
                price: 0x3c,
                sellNum: 0xda,
                type: 0x0,
                typeName: "",
                unit: "GB",
                dateUnit: "月",
                name: "30GB",
                reFlow: "30GB",
                productId: "91326542",
                productName: "黑龙江-60元30GB国内5G流量月包（立即生效）",
                path: "orderPage",
            },
            {
                flow: 0x5,
                price: 0x13,
                sellNum: 0x151,
                type: 0x1,
                typeName: "升级包",
                unit: "GB",
                dateUnit: "月",
                name: "5GB",
                reFlow: "5GB",
                productId: "90778507",
                productName: "5G升级包19元5GB（立即生效）",
                path: "orderPage",
            },
            {
                flow: 0xa,
                price: 0x1d,
                sellNum: 0x246,
                type: 0x1,
                typeName: "升级包",
                unit: "GB",
                dateUnit: "月",
                name: "10GB",
                reFlow: "10GB",
                productId: "90759221",
                productName: "5G升级包29元10G（立即生效）",
                path: "orderPage",
            },
            {
                flow: 0x14,
                price: 0x31,
                sellNum: 0x124,
                type: 0x1,
                typeName: "升级包",
                unit: "GB",
                dateUnit: "月",
                name: "20GB",
                reFlow: "20GB",
                productId: "90759226",
                productName: "5G升级包49元20G（立即生效）",
                path: "orderPage",
            },
            {
                flow: 0x19,
                price: 0x20,
                sellNum: 0x1ab,
                commId: "974203297374",
                templateFlag: "1",
                type: 0x0,
                typeName: "",
                unit: "GB",
                reFlow: "25GB",
                dateUnit: "月",
                name: "25GB",
                productId: "91326526",
                productIds: ["91326532"],
                productName: "32元25GB月包(特惠组合版)",
                path: "orderPage",
            },
            {
                flow: 0x14,
                price: 0x1f,
                sellNum: 0x101,
                commId: "974203297376",
                templateFlag: "1",
                type: 0x0,
                typeName: "",
                unit: "GB",
                reFlow: "20GB",
                dateUnit: "月",
                name: "20GB",
                productId: "91326526",
                productIds: ["91326533"],
                productName: "31元20GB月包(特惠组合版)",
                path: "orderPage",
            },
            {
                flow: 0x1e,
                price: 0x2a,
                sellNum: 0x101,
                commId: "974203297377",
                templateFlag: "1",
                type: 0x0,
                typeName: "",
                unit: "GB",
                reFlow: "30GB",
                dateUnit: "月",
                name: "30GB",
                productId: "91326528",
                productIds: ["91326532"],
                productName: "42元30GB月包(特惠组合版)",
                path: "orderPage",
            },
            {
                flow: 0x19,
                price: 0x29,
                sellNum: 0x23c,
                commId: "974203297378",
                templateFlag: "1",
                type: 0x0,
                typeName: "",
                unit: "GB",
                reFlow: "25GB",
                dateUnit: "月",
                name: "25GB",
                productId: "91326528",
                productIds: ["91326533"],
                productName: "41元25GB月包(特惠组合版)",
                path: "orderPage",
            },
        ],
    },
    {
        id: 0xc,
        text: "夜间包",
        children: [
            {
                flow: 0xa,
                price: 0xa,
                sellNum: 0x60c,
                type: 0x0,
                typeName: "",
                unit: "GB\x20夜间包",
                dateUnit: "月",
                name: "10GB",
                reFlow: "10GB",
                productId: "91258931",
                productName: "10元10GB夜间包（立即生效）",
                path: "orderPage",
            },
            {
                flow: 0x14,
                price: 0x14,
                sellNum: 0x60c,
                type: 0x2,
                typeName: "推荐",
                unit: "GB\x20夜间包",
                dateUnit: "月",
                name: "20GB",
                reFlow: "20GB",
                productId: "91258936",
                productName: "20元20GB夜间包（立即生效）",
                path: "orderPage",
            },
        ],
    },
];
