name: "更新账号accessToken"
run-name: "OP要喝OP果奶"
on:
    schedule:
        - cron: '0 0 */5 * *' # 每5天运行一次
    workflow_dispatch: # 允许手动触发工作流
jobs:
    run-python-script:
        runs-on: ubuntu-latest
        steps:
      
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: script-update run
              run: python main.py update
